# Importing Libraries

In [1]:
#import os
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
#from sklearn import svm
#import sklearn.cross_validation
from sklearn.model_selection import train_test_split
from numpy import random
from sklearn.preprocessing import LabelEncoder
from nltk.corpus import stopwords
from sklearn.metrics import classification_report
from sklearn import svm
import warnings
warnings.filterwarnings('ignore')
import gensim
from gensim.models import Word2Vec

# Loading the Train Data

In [2]:
data = pd.read_excel('Mortein train data ECOM(New).xlsx',sheet_name="Train1")
data.columns

Index(['Mention Content', 'Level1', 'Level2', 'Level3'], dtype='object')

# Data Cleaning

In [3]:
print("\t###### Encoding Target Variable ######\t\n")    
lb_make = LabelEncoder()
data["lable_code"] = lb_make.fit_transform(data['Level3'].astype(str))

data["lable_code"].describe()

	###### Encoding Target Variable ######	



count    25842.000000
mean        39.795991
std         21.946075
min          0.000000
25%         31.000000
50%         36.000000
75%         57.000000
max         81.000000
Name: lable_code, dtype: float64

In [4]:
# converting all messages to lower case
data['Mention Content']=data['Mention Content'].str.lower()

In [78]:
 # Replace email addresses with 'email'
#data['Mention Content']=data['Mention Content'].str.replace(r'^.+@[^\.].*\.[a-z]{2,}$','emailaddress')

In [79]:
# Replace URLs with 'webaddress'
# Replace money symbols with 'moneysymb'(£ can be typed with ALT + 156# Replace money symbols with 'moneysymb'(£ can be typed with ALT + 156
#data['Mention Content']=data['Mention Content'].str.replace(r'^http\://a[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(/\S*)?$',
 #                                           'webaddress')


In [80]:
 # Replace money symbols with 'moneysymb'(£ can be typed with ALT + 156
#data['Mention Content']=data['Mention Content'].str.replace(r'£|\$','dollers')


In [81]:
# Replace 10 didgit phone numbers(formats include paranthesis, spaces, no spaces, dashes) with 'phonenumber'
#data['Mention Content']=data['Mention Content'].str.replace(r'^\(?[\d]{3}\)?[\s-]?[\d]{3}[\s-]?[\d]{d}','phonenumber')

In [82]:
# replace numbers with 'numbr'
#data['Mention Content']=data['Mention Content'].str.replace(r'\d+(\.\d+)?','numbr')

In [83]:
# remove punctuation
#data['Mention Content']=data['Mention Content'].str.replace(r'[^\w\d\s]',' ')

In [84]:
# Replace whitespace between terms with a single space
#data['Mention Content']=data['Mention Content'].str.replace(r'\s+',' ')

In [85]:
# Remove Leading and trailing whitespace
#data['Mention Content']=data['Mention Content'].str.replace(r'^\s+|\s+?$',' ')

In [5]:
data_x = data['Mention Content'].values.tolist()
data_y = np.asarray(data['lable_code'],dtype=int)

In [6]:
stopset = set(stopwords.words('english'))


In [7]:
print("\t###### Converting Text to Feature Vector ######\t\n")    
cv =  CountVectorizer(lowercase=True,stop_words=stopset, ngram_range=(1,3))
X_traincv = cv.fit_transform(str(e) for e in data_x)

	###### Converting Text to Feature Vector ######	



# Train Test Split and Model Building

In [8]:
#train_x,test_x,train_y,test_y=train_test_split(X_traincv,data_y,test_size=0.4)

In [9]:
x_train, x_test, y_train, y_test=train_test_split(X_traincv, data_y ,random_state=47, test_size=0.4)

In [10]:
#from sklearn.linear_model import LogisticRegression
#from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
#from sklearn.naive_bayes import GaussianNB
#from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import ExtraTreesClassifier, GradientBoostingClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import ComplementNB

In [92]:
# Gradient Boosting Classifier
#gbt=GradientBoostingClassifier()
#gbt.fit(x_train,y_train)
#pred_y=gbt.predict(x_test)
#print('accuracy score',accuracy_score(y_test,pred_y))
#print("confusion matrix")
#print(confusion_matrix(y_test,pred_y))
#print('classification',classification_report(y_test,pred_y)) 
# Probablity
#print('gbt_prob',gbt.predict_proba(x_test))

In [11]:
# SGDClassifier
sgd=SGDClassifier(loss='hinge',class_weight='balanced')
sgd.fit(x_train,y_train)
pred_y=sgd.predict(x_test)
print('accuracy score',accuracy_score(y_test,pred_y))
print("confusion matrix")
print(confusion_matrix(y_test,pred_y))
print('classification',classification_report(y_test,pred_y))
# Probablity
#print('sgd_prob',sgd.predict_proba(x_test))


accuracy score 0.8454096933346232
confusion matrix
[[960   7   0 ...   0   2   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...  39   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   1]]
classification               precision    recall  f1-score   support

           0       0.78      0.94      0.85      1019
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         2
           4       0.44      0.70      0.54        10
           5       0.00      0.00      0.00         0
           6       0.67      0.55      0.60        40
           7       1.00      0.83      0.91        24
           8       0.88      0.72      0.79        53
           9       0.97      0.63      0.76        46
          10       0.86      0.95      0.90       194
          11       0.89      0.40      0.55        43
          12       0.00      0.00      

In [94]:
# SGD Classifier Cross Validation
#score=cross_val_score(sgd,x_train,y_train,cv=10)
#print('cv score',np.mean(score))

In [12]:
# ComplementNB
cnb=ComplementNB()
cnb.fit(x_train,y_train)
pred_y=cnb.predict(x_test)
print('accuracy score',accuracy_score(y_test,pred_y))
print("confusion matrix")
print(confusion_matrix(y_test,pred_y))
print('classification',classification_report(y_test,pred_y))
# Probablity
print('cnb_prob',cnb.predict_proba(x_test))


accuracy score 0.803714810873561
confusion matrix
[[857   1   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...  26   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   1]]
classification               precision    recall  f1-score   support

           0       0.86      0.84      0.85      1019
           1       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         2
           4       0.60      0.30      0.40        10
           5       0.00      0.00      0.00         0
           6       0.82      0.35      0.49        40
           7       0.61      0.83      0.70        24
           8       0.72      0.74      0.73        53
           9       0.74      0.57      0.64        46
          10       0.81      0.91      0.86       194
          11       0.79      0.44      0.57        43
          12       0.00      0.00      0.00         1
          14       0.00      0.00      0

In [47]:
# CNB Classifier Cross Validation
#score=cross_val_score(cnb,x_train,y_train,cv=10)
#print('cv score',np.mean(score))

In [48]:
# Extra Trees Classifier
#etc=ExtraTreesClassifier()
#etc.fit(x_train,y_train)
#pred_y=etc.predict(x_test)
#print('accuracy score',accuracy_score(y_test,pred_y))
#print("confusion matrix")
#print(confusion_matrix(y_test,pred_y))
#print('classification',classification_report(y_test,pred_y))
# Probablity
#print('etc_prob',etc.predict_proba(x_test))

In [13]:
# MultinomialNB
mnb=MultinomialNB()
mnb.fit(x_train,y_train)
pred_y=mnb.predict(x_test)
print('accuracy score',accuracy_score(y_test,pred_y))
print("confusion matrix")
print(confusion_matrix(y_test,pred_y))
print('classification',classification_report(y_test,pred_y))
mnb.predict_proba(x_test)
# Probablity
print('mnb_prob',mnb.predict_proba(x_test))

accuracy score 0.7636645061429815
confusion matrix
[[799   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   3 ...   0   0   0]
 ...
 [  0   0   0 ...  15   0   0]
 [  0   0   0 ...   0   0   0]
 [  1   0   0 ...   0   0   0]]
classification               precision    recall  f1-score   support

           0       0.92      0.78      0.85      1019
           3       0.00      0.00      0.00         2
           4       0.60      0.30      0.40        10
           6       1.00      0.05      0.10        40
           7       1.00      0.42      0.59        24
           8       1.00      0.32      0.49        53
           9       1.00      0.24      0.39        46
          10       0.94      0.75      0.84       194
          11       1.00      0.14      0.24        43
          12       0.00      0.00      0.00         1
          14       0.00      0.00      0.00         5
          16       0.95      0.79      0.86       227
          17       0.97      0.81      

In [50]:
#print("\t###### Building  Model ######\t\n")    
#nbayes = MultinomialNB()
#nbayes.fit(train_x,train_y)
#from sklearn.ensemble import RandomForestClassifier

#pred=nbayes.predict(test_x)
#accuracy_score(pred,test_y)

# Loading the Test Data

In [14]:
test_data = pd.read_excel('Mortein train data ECOM(New).xlsx',sheet_name="Test1")

test_data1 = test_data['Review']

In [15]:
test_data.columns

Index(['ID', 'Review'], dtype='object')

In [16]:
test_data

ID                                             Review
0      1                       It is superb. Thenks Amazon.
1      2                                           Not good
2      3  They are selling scented oils. Mosquitoes is r...
3      4  They are selling scented oils. Mosquitoes is r...
4      5                      Poor quality low quality feak
..   ...                                                ...
993  994  Mice haven't touched the wrapped inner packet....
994  995                         Never touch a mouse again!
995  996  (PT) Gostei muito,produto muito bom,preço exce...
996  997                                        Works great
997  998                                        Works great

[998 rows x 2 columns]

# Prediction on Test Data(Best Model)

In [17]:
print("\t###### Converting Text to Feature Vector ######\t\n")
test_prediction = cv.transform(str(i) for i in test_data1)

	###### Converting Text to Feature Vector ######	



In [18]:
# Prediction on best Model
print("\t###### Predicting SMS Text ######\t\n")
test_prediction = sgd.predict(test_prediction)

	###### Predicting SMS Text ######	



In [19]:
predict_labels = pd.Series(lb_make.inverse_transform(test_prediction))

In [20]:
#output1=output1.drop(['Level1_x'], axis = 1)

In [21]:
output1 = pd.DataFrame({'ID':test_data['ID'], 'Text1':test_data['Review'],
                       'Level3':predict_labels})

#output.to_excel('Lysol_p.xlsx',index=False)

In [22]:

output1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998 entries, 0 to 997
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   ID      998 non-null    int64 
 1   Text1   998 non-null    object
 2   Level3  998 non-null    object
dtypes: int64(1), object(2)
memory usage: 23.5+ KB


# Leveling the Data

In [23]:
test1 = pd.read_excel('Mortein train data ECOM(New).xlsx',sheet_name="t3")

In [24]:
#test1

In [25]:
test1.columns

Index(['Level1', 'Level2', 'Level3'], dtype='object')

In [26]:
output1=pd.merge(output1,test1,on='Level3',how='left')


In [27]:
output1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 998 entries, 0 to 997
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   ID      998 non-null    int64 
 1   Text1   998 non-null    object
 2   Level3  998 non-null    object
 3   Level1  981 non-null    object
 4   Level2  981 non-null    object
dtypes: int64(1), object(4)
memory usage: 46.8+ KB


In [28]:
pd.crosstab(index=output1["Level3"],columns="count") 

col_0                             count
Level3                                 
1 Word Positive Feedback            111
1 word Positive Feedback              1
Appreciate Consistency                1
Appreciate Delivery                  10
Appreciate Durability                 2
Appreciate Packaging                  6
Appreciate Quality                    6
Choking                               3
Claims of Counterfeit Product         8
Damaged/Broken                        3
Defective Product                     5
Delivery Man                          2
Delivery Service Issue                5
Difficult to Set/Use                  4
Dislike Design                        2
Dislike Packaging                     1
Dislike Stickiness                    1
Easy to Set/Use                      18
Effective in Repelling/Killing      101
Expensive                             3
General Comments                    311
General Complaints                   32
Human Harm                            2
Hurting                               2
Ineffective in Repelling/Killing     62
Itching                               1
Leaked Product                        3
Missing Product                       3
Non-Durable                           8
Not/Stopped Working                   6
Open/Unsealed Product                 1
Opened/Unsealed Product               1
Pleasant Fragrance                    1
Poison                                2
Poor Battery Life                     1
Poor Quality                          1
Product Appreciation                115
Product/Usage Enquiry                 6
Quick Delivery                       51
Sick                                  1
Spark                                 5
Strong Smell                         11
Usage Suggestion                      1
Value for Money                      76
Weak/No Smell                         1
Wrong Delivery                        1

In [29]:
output1

ID                                              Text1  \
0      1                       It is superb. Thenks Amazon.   
1      2                                           Not good   
2      3  They are selling scented oils. Mosquitoes is r...   
3      4  They are selling scented oils. Mosquitoes is r...   
4      5                      Poor quality low quality feak   
..   ...                                                ...   
993  994  Mice haven't touched the wrapped inner packet....   
994  995                         Never touch a mouse again!   
995  996  (PT) Gostei muito,produto muito bom,preço exce...   
996  997                                        Works great   
997  998                                        Works great   

                               Level3                  Level1  \
0            1 Word Positive Feedback      Product Perception   
1            1 Word Positive Feedback      Product Perception   
2       Claims of Counterfeit Product      Product Perception   
3       Claims of Counterfeit Product      Product Perception   
4                        Poor Quality  Manufacturing & Design   
..                                ...                     ...   
993  Ineffective in Repelling/Killing           Functionality   
994  Ineffective in Repelling/Killing           Functionality   
995                   Value for Money                 Pricing   
996          1 Word Positive Feedback      Product Perception   
997          1 Word Positive Feedback      Product Perception   

                                           Level2  
0                        1 Word Positive Feedback  
1                        1 Word Positive Feedback  
2                   Claims of Counterfeit Product  
3                   Claims of Counterfeit Product  
4    Defective/ Non-Durable/ Poor Quality Product  
..                                            ...  
993              Ineffective in Repelling/Killing  
994              Ineffective in Repelling/Killing  
995                               Value for Money  
996                      1 Word Positive Feedback  
997                      1 Word Positive Feedback  

[998 rows x 5 columns]

# Saving the  model

In [30]:
writer = pd.ExcelWriter(r'Mortein clare sgd may.xlsx', engine='xlsxwriter',options={'strings_to_urls': False})
output1.to_excel(writer)
writer.close()

In [ ]:
import googletrans
print(googletrans.LANGUAGES)